version: "2"
services:
    api:
        image: dmitrovskiy/docker-nginx-php-fpm:1.0.0-alpine
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
    mysql:
        image: mysql:8.0.0
        volumes:
          - ./data/mysql:/var/lib/mysql
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=password
