version: "2"
services:
    api:
        build: _build/.
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
        environment:
            - PHP_XDEBUG_ENABLED=1
    mysql:
        image: mysql:8.0.0
        volumes:
          - ./data/mysql:/var/lib/mysql
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=password
